/**
 * Site content — generated from cvitae/data/master.yaml
 * DO NOT EDIT THIS FILE MANUALLY.
 */
window.SITE_CONTENT = {
    "meta": {
        "title": "Isaac Houngue | Software & Research Engineer"
    },
    "header": {
        "logo": "you're@hjisaac"
    },
    "nav": [
        {
            "href": "#experiences",
            "label": "#experience"
        },
        {
            "href": "#education",
            "label": "#education"
        },
        {
            "href": "#skills",
            "label": "#skills"
        },
        {
            "href": "#projects",
            "label": "#projects"
        },
        {
            "href": "#contact",
            "label": "#contact"
        },
        {
            "href": "#papers",
            "label": "#papers"
        }
    ],
    "intro": {
        "greeting": "I'm Isaac H. J. Houngue,",
        "roleHighlight": "a software & research engineer.",
        "headshot": "./assets/images/headshot_lower.jpg",
        "headshotAlt": "Isaac Houngue"
    },
    "summary": "Motivated Software and Research Engineer with MSc backgrounds in Artificial Intelligence and Computer Science. I combine 3+ years of software engineering with research experience in machine learning and scientific AI — building intelligent systems that are simple, robust, and useful.\n",
    "sections": {
        "experience": {
            "id": "experiences",
            "title": "#experience",
            "theme": "light",
            "entries": [
                {
                    "role": "Apprentice Research Engineer",
                    "organization": "InstaDeep",
                    "dates": "Jul 2025 – Present",
                    "location": "South Africa, hybrid",
                    "bullets": [
                        "Evaluated fine-tuning strategies for adapting InstaNovo, a transformer-based de novo peptide sequencing model, to glycopeptide sequencing tasks.",
                        "Explored contrastive learning, multi-task learning, knowledge distillation, curriculum learning, and transformer-variant architectures to improve sequencing performance.",
                        "Designed modular, pluggable components inspired by research papers to accelerate hypothesis testing and integration of new modeling approaches.",
                        "Conducted large-scale experiments and ablation studies on architectural choices, training strategies, and model components.",
                        "Designed synthetic glycopeptide datasets and multi-stage training strategies to improve representation learning and transfer to experimental tasks.",
                        "Performed glycopeptide spectral dataset analysis and feature selection studies to understand data characteristics and model limitations.",
                        "Documented research findings through technical reports, visualizations, and presentations."
                    ],
                    "organizationUrl": "https://instadeep.com/",
                    "meta": "Jul 2025 – Present · South Africa, hybrid"
                },
                {
                    "role": "Backend Software Engineer",
                    "organization": "Fasfox",
                    "dates": "Mar 2023 – Sep 2024",
                    "location": "Paris, remote",
                    "bullets": [
                        "Enhanced the backend API of Concrete Dispatch SaaS, a logistics platform for managing concrete deliveries (Django/DRF).",
                        "Improved a fiber ordering and tracking product for AXIONE (Django/DRF).",
                        "Developed a fault-tolerant daemon for parsing large CSV and eligibility data files for Fiber Dispatch (Django/Ninja).",
                        "Built TMForum compliant endpoints for fiber order handling following interop protocols (Django/Ninja).",
                        "Applied web scraping and AI-powered OCR to extract data from PDFs for real-time validation (Django/DRF).",
                        "Built and maintained a daemon that listens to email inboxes and parses attachments to create objects across databases (Django/DRF)."
                    ],
                    "organizationUrl": "https://fasfox.com/",
                    "meta": "Mar 2023 – Sep 2024 · Paris, remote"
                },
                {
                    "role": "Frontend Software Engineer",
                    "organization": "Fasfox",
                    "dates": "Oct 2021 – Feb 2023",
                    "location": "Paris, remote",
                    "bullets": [
                        "Maintained and enhanced Concrete Dispatch SaaS PWAs: photo uploads, digital signatures, QR scanning, and interactive graphs (Vue.js/Nuxt.js).",
                        "Developed an advanced slider for concrete volume tracking in the desktop web app (React.js/Next.js).",
                        "Built an efficient concrete calculator for the Concrete Dispatch blog site (Hugo/JavaScript)."
                    ],
                    "organizationUrl": "https://fasfox.com/",
                    "meta": "Oct 2021 – Feb 2023 · Paris, remote"
                },
                {
                    "role": "Software Engineering Intern",
                    "organization": "National Civil Aviation Agency",
                    "dates": "Aug 2019 – Sep 2019",
                    "location": "Benin, onsite",
                    "bullets": [
                        "Developed a Python/Tkinter inventory management desktop application for tracking electronic equipment.",
                        "Assisted in maintenance of office and IT equipment."
                    ],
                    "organizationUrl": "https://anac.bj/",
                    "meta": "Aug 2019 – Sep 2019 · Benin, onsite"
                }
            ]
        },
        "education": {
            "id": "education",
            "title": "#education",
            "theme": "dark",
            "entries": [
                {
                    "title": "Master in Artificial Intelligence — African Institute for Mathematical Sciences (AIMS)",
                    "meta": "Sep 2024 – Jul 2025",
                    "bullets": [
                        "Coursework: Bayesian Inference, Machine Learning at Scale, Computer Vision, Reinforcement Learning, Deep Generative Models, Engineering LLMs, CUDA Programming, and more.",
                        "Thesis: Advancing De Novo Glycopeptide Sequencing with InstaNovo in Glycoproteomics."
                    ]
                },
                {
                    "title": "Master in Computer Science — Institute of Mathematics and Physical Sciences (IMSP)",
                    "meta": "Oct 2018 – Jul 2020",
                    "bullets": [
                        "Coursework: Advanced Data Structures and Algorithms, Operating Systems, Software Architecture, Distributed Databases, Artificial Intelligence, Machine Learning and more.",
                        "Thesis: A Smart Contract-based Remote Voting Platform using Blind Signature."
                    ]
                }
            ]
        },
        "skills": {
            "id": "skills",
            "title": "#skills",
            "theme": "light",
            "groups": [
                {
                    "label": "Programming Languages",
                    "items": "Python, JavaScript, TypeScript"
                },
                {
                    "label": "Frameworks & Libraries",
                    "items": "Django, DRF, Flask, Ninja, Node.js, Vue.js, React.js, Next.js, GraphQL, PyTorch, Keras"
                },
                {
                    "label": "Infrastructure & Tools",
                    "items": "Linux, Git, Docker, GCP, AWS, Kafka, Spark, PostgreSQL, MongoDB, Neo4j"
                }
            ]
        },
        "projects": {
            "id": "projects",
            "title": "#projects",
            "theme": "dark",
            "entries": [
                {
                    "title": "Run Crucible",
                    "meta": "Feb 2026 – Present",
                    "summary": "Modular framework for managing and comparing machine learning experiments across training configurations and model architectures.",
                    "tools": [
                        "Python",
                        "PyTorch",
                        "Hydra",
                        "Docker"
                    ],
                    "github": "https://github.com/hjisaac/run-crucible",
                    "bullets": null
                },
                {
                    "title": "Billvoicer",
                    "meta": "Jan 2023 -- Now",
                    "summary": "Initiator and principal engineer of Billvoicer, driving the project's vision and technical development.",
                    "tools": [
                        "Python (Django/Drf)",
                        "VueJS/NuxtJS",
                        "PostgreSQL",
                        "Redis",
                        "Celery"
                    ],
                    "github": null,
                    "bullets": [
                        "Leading architecture design, feature development, and technology decisions.",
                        "Managing a team of interns, overseeing development activities, issue tracking, code reviews and more.",
                        "Ensuring seamless team communication and alignment with the product roadmap."
                    ]
                }
            ]
        },
        "contact": {
            "id": "contact",
            "title": "#contact",
            "theme": "light",
            "entries": [],
            "form": {
                "action": "https://formspree.io/f/xvonzgnq",
                "method": "POST"
            },
            "prompt": "I'm always open to discussing new projects, research opportunities, or just having a chat. Feel free to reach out!"
        },
        "papers": {
            "id": "papers",
            "title": "#papers",
            "theme": "dark",
            "entries": []
        }
    },
    "footer": {}
};
