import json
import os
import sys
import yaml
from pydantic import BaseModel, ValidationError
from typing import List, Dict, Optional, Any

class WebsiteContentSchema(BaseModel):
    meta: Dict[str, str]
    header: Dict[str, str]
    nav: List[Dict[str, str]]
    intro: Dict[str, str]
    summary: str
    sections: Dict[str, Any]
    footer: Dict[str, Any]

def sync():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cv_data_path = os.path.join(root, 'data/cvitae/dist/master.json')
    meta_path = os.path.join(root, 'data/site_meta.yaml')
    output_path = os.path.join(root, 'js/content.js')

    if not os.path.exists(cv_data_path):
        print(f"Error: CV data not found at {cv_data_path}")
        sys.exit(1)

    with open(cv_data_path, 'r') as f:
        cv_data = json.load(f)
    
    with open(meta_path, 'r') as f:
        meta = yaml.safe_load(f)

    try:
        content = {
            "meta": meta["meta"],
            "header": meta["header"],
            "nav": meta["nav"],
            "intro": meta["intro"],
            "summary": cv_data["summary"].get(meta.get("summary_key", "general"), ""),
            "sections": {},
            "footer": meta.get("footer", {})
        }

        for sec_key, sec_config in meta["sections"].items():
            resolved_sec = {"id": sec_config["id"], "title": sec_config["title"], "theme": sec_config["theme"], "entries": []}
            
            if sec_key == 'experience':
                for item_id in sec_config.get("items", []):
                    # Fixed: Use 'experience' key which exists in cv_data
                    entry = cv_data["experience"][item_id].copy()
                    entry['organizationUrl'] = entry.pop('organization_url', None)
                    entry['meta'] = f"{entry['dates']} · {entry['location']}"
                    resolved_sec["entries"].append(entry)
            
            elif sec_key == 'education':
                for item_id in sec_config.get("items", []):
                    entry = cv_data["education"][item_id]
                    resolved_sec["entries"].append({"title": f"{entry['degree']} — {entry['organization']}", "meta": entry['dates'], "bullets": entry['bullets']})

            elif sec_key == 'projects':
                for item_id in sec_config.get("items", []):
                    entry = cv_data["projects"][item_id]
                    resolved_sec["entries"].append({"title": entry['title'], "meta": entry['dates'], "summary": entry['summary'], "tools": entry['tools'], "github": entry['url'] if not entry.get('private') else None, "bullets": entry.get('bullets')})

            elif sec_key == 'skills':
                del resolved_sec["entries"]
                resolved_sec["groups"] = []
                # Fixed: Use 'skills' key which exists in cv_data
                for cat, items in cv_data["skills"].items():
                    resolved_sec["groups"].append({"label": cat.replace('_', ' ').title(), "items": ", ".join(items)})

            elif sec_key == 'contact':
                resolved_sec["form"] = {"action": "https://formspree.io/f/xvonzgnq", "method": "POST"}
                resolved_sec["prompt"] = "I'm always open to discussing new projects, research opportunities, or just having a chat."
            
            content["sections"][sec_key] = resolved_sec

        WebsiteContentSchema(**content)
        js_output = f"/** AUTO-GENERATED BY sync.py **/\nwindow.SITE_CONTENT = {json.dumps(content, indent=4, ensure_ascii=False)};"
        with open(output_path, 'w') as f:
            f.write(js_output)
        print(f"✅ Published updated content to {output_path}")

    except ValidationError as e:
        print("❌ Validation Failed!")
        print(e)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error during sync: {e}")
        sys.exit(1)

if __name__ == '__main__':
    sync()
